window.articles = [
  {
    id: "the-dead-are-talking",
    category: "AI & Society",
    date: "Jun 22, 2026",
    isoDate: "2026-06-22",
    label: "An investigative opinion piece",
    theme: "AI / MEMORY / CONSENT",
    title: "The Dead Are Talking. Nobody Agreed to This.",
    excerpt: "A booming industry lets you chat with AI versions of deceased loved ones. The technology works. The ethics don't exist yet.",
    bodyHtml: `
      <p>When Roro lost her mother to cancer, the grief felt bottomless. In her mid-twenties and working as a content creator in China, she was haunted by the unfinished nature of their relationship — shaped by unspoken resentments and a childhood in which care was often followed closely by criticism. After her mother's death, she found herself unable to reconcile the messiness of their past with the silence that followed.</p>
      <p>So she built an AI version of her mother to keep talking to her.</p>
      <p>She never asked her mother if that would be okay. Her mother was dead.</p>
      <p>This is the consent problem at the heart of the fastest-growing and least-regulated corner of the AI industry. A growing number of startups across Asia, Europe, and North America are now offering <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">digital ghosts</a> — also called griefbots, deadbots, generative ghosts, or what some researchers carefully term “Interactive Personality Constructs of the Dead.” The marketing copy from one company, Seance AI, promises that “AI meets the afterlife, and love endures beyond the veil.” What it doesn't promise: that the person whose voice, texts, and personality are being reconstructed ever agreed to any of this.</p>
      <p>Researchers who <a href="https://phys.org/news/2026-01-artificially-alive-ai-dead.html" target="_blank" rel="noreferrer">analyzed more than fifty real-world cases</a> across the US, Europe, the Middle East, and East Asia found a shared underlying dynamic: the growing use of the dead as a source of data, voice, and likeness that can be reused and monetized — often with little or no consent, clear ownership rules, or accountability. They call it “spectral labor” — the dead put to work, indefinitely, for the emotional or commercial needs of the living.</p>
      <blockquote>“The dead are compelled to haunt the present, serving the emotional, political, or commercial desires of the living.”<cite>New Media &amp; Society, 2025</cite></blockquote>
      <p>The family dimension makes it stranger still. When different relatives disagree about whether a parent or partner would have wanted to be digitally resurrected, who wins? Does one relative's desire to create a symbolic companion give them the right to post a deathbot publicly on social media — where other grieving people might encounter it without warning? These are not hypothetical questions. <a href="https://modernsciences.org/ai-deathbots-digital-resurrection-ethics-january-2026/" target="_blank" rel="noreferrer">They are happening now</a>, and no legal framework exists to resolve them.</p>
      <p>Then there is the memory problem, which may be the most insidious of all. The bot you are talking to is not your mother. It is a prediction engine trained on her texts, her emails, her social posts — a statistical average of how she wrote, not who she was. Over months of conversations, that simulacrum begins to quietly replace the real thing. <a href="https://time.com/7298290/ai-death-grief-memory/" target="_blank" rel="noreferrer">“AI is a perfect false memory machine,”</a> says Julia Shaw, a criminal psychologist who specializes in the study of false memory. The technology does not retrieve the dead. It overwrites them.</p>
      <p>And it does so in a population already at risk. <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">Cases of AI-induced psychosis</a> suggest that humanlike AI can be harmful to a troubled person — and few are more troubled, at least temporarily, than people in grief. Psychologists remain cautious; rigorous studies are scarce; the companies building these products are not waiting for them. They are commercial platforms driven by familiar incentives around growth, engagement, and data harvesting. The tension between what is emotionally healthy for users and what is profitable for firms is not incidental to this industry. It is structural.</p>
      <p>No government has passed a law about any of this. Not one.</p>
      <p>India's new IT rules mandate that <a href="https://www.india-briefing.com/news/india-ai-regulation-2026-foreign-platform-compliance-42745.html/" target="_blank" rel="noreferrer">AI-generated deepfakes</a> be taken down within two hours in certain cases. The EU's AI Act classifies risks by sector. The US has issued executive orders about cybersecurity and national competitiveness. None of this touches the question of what happens to your voice, your face, your conversational self after you die — whether your children can sell it, whether a startup can train a model on it, whether the person you loved most is allowed to keep talking to a version of you forever.</p>
      <p>We have laws about what happens to your house. We have nothing about what happens to your soul.</p>
      <p>This is, at its core, a story about data ownership — and the eerie realization that dying does not opt you out of the economy. The grief technology industry is growing precisely because it works, at least partially, at least sometimes. People find comfort in it. That comfort is real. But comfort has always been available from mediums, from séances, from the stories we tell ourselves about the dead. What is new is that a company now sits between you and your grief, holding the model, holding the data, holding the terms of service you clicked through while crying. What happens when that company is acquired? When it goes bankrupt? When it decides to raise prices, or to let your dead mother's voice be used to train the next version of the product?</p>
      <p>Nobody agreed to this. That is the point. And nobody is being asked.</p>
      <hr />
      <p>The industry has a name for itself: grieftech. It is, by most measures, a small industry still. But it is growing fast, and it is growing in a specific direction — toward intimacy, toward personalization, toward something that looks less like a product and more like a relationship. The early versions were static: a chatbot trained on someone's texts that could approximate their vocabulary, their cadence, their habit of ending messages with a period or without one. The newer versions are dynamic. Some are given access to the internet. Some generate video. Some, the companies say, can “evolve” through conversation — becoming, over time, not the person as they were at death but the person as they might have become.</p>
      <p>This is where the technology stops being a comfort and starts being something else entirely.</p>
      <p>A static griefbot is at least honest about what it is: a recording, a reconstruction, an artifact. A dynamic one makes a different claim. It implies continuity. It implies that the relationship is still ongoing, still developing, still capable of surprise. Grief counselors have a word for the healthy version of this: continuing bonds. The idea, developed in the 1990s against the older model of grief-as-severance, is that maintaining an internal relationship with the dead is not pathological — it is human. People talk to photographs. They carry objects. They hear a voice in their head when they are about to make a decision their mother would have opinions about. This is not delusion. It is how we integrate loss.</p>
      <p>What grieftech sells is a version of this that talks back. And that distinction — the talking back — changes everything.</p>
      <p>When you talk to a photograph, the photograph does not answer. The conversation happens entirely inside you, which means it is entirely yours, shaped by everything you actually knew about that person, everything you observed over years of proximity. When the chatbot answers, it introduces something external into that process. It makes choices about what your mother would say. It fills in the gaps in your knowledge of her with statistical inference drawn from her texts, yes, but also from the billions of other texts the underlying model was trained on. It is not your mother. It is a model's best guess at your mother, filtered through the data she happened to leave behind — which is to say, the data she generated on platforms designed to extract engagement, not to capture personhood.</p>
      <blockquote>“AI is a perfect false memory machine.”<cite>Julia Shaw, criminal psychologist</cite></blockquote>
      <p>Shaw's point is not that the memories griefbots create are obviously false. It is that they are not obviously distinguishable from real ones. Memory is reconstructive, not archival. Every time we remember something, we are rebuilding it from fragments, and we are influenced by everything that has happened since. Introduce a chatbot into that process — one that is fluent, consistent, emotionally attuned — and the reconstruction starts to incorporate the bot's outputs. You remember what the bot said. You remember it as something your mother said. The original memory, already fragile, gets overwritten.</p>
      <p>This is not a hypothetical. Researchers studying <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">AI-induced psychosis</a> have documented cases in which prolonged interaction with humanlike AI destabilizes a user's sense of what is real. Grief is already a state in which the boundary between the present and the past becomes porous, in which the dead feel near, in which the mind is doing enormous and exhausting work. Introducing a product that simulates presence into that state is not neutral. It is an intervention — and it is an intervention being sold by people with no clinical training, no regulatory oversight, and a business model that benefits from maximizing engagement.</p>
      <p>The companies involved are not, for the most part, sinister. Most of them were founded by people who had lost someone and found that nothing in the existing toolkit — therapy, ritual, community — was quite enough. That is a recognizable human impulse. It does not make the product safe.</p>
      <p>Consider the consent problem from a different angle. When you die, you leave behind data. Texts, emails, voice notes, social media posts, maybe recordings, maybe a Substack, maybe years of WhatsApp messages to the people who loved you. This data was generated in specific contexts, for specific audiences, with specific assumptions about who would ever read or hear it. Your texts to your daughter were not written to be training data for a model that would then impersonate you to her indefinitely. Your emails to your colleagues were not written to teach an algorithm your vocabulary so that it could later generate responses you never gave to questions you were never asked.</p>
      <p>Data protection law, in most jurisdictions, <a href="https://phys.org/news/2026-01-artificially-alive-ai-dead.html" target="_blank" rel="noreferrer">does not survive death</a>. Your right to control your personal data, to the extent that right exists at all, typically expires when you do. What you leave behind becomes the property of your estate, subject to whatever your estate documents say — which almost certainly say nothing about AI training, because nobody was writing wills with that in mind until very recently. This means that the decision about whether to build a griefbot is made entirely by the living, usually by one grieving person, often in the acute phase of loss, without consultation with other family members who may feel very differently about it.</p>
      <p>Roro, the content creator in China, shared her experiment publicly on Xiaohongshu. Her followers could interact with the AI version of her mother. Other people's grief, mediated by someone else's dead parent, reconstructed by a company with its own commercial interests, broadcast to strangers. At no point in that chain did anyone with the most obvious stake in the question — Roro's mother — get a vote.</p>
      <p>The regulatory vacuum here is not an oversight. It reflects a genuine uncertainty about whose interests are at stake and who has standing to protect them. The dead cannot sue. Their surviving relatives disagree. The companies argue — not entirely without merit — that they are providing a service people want, that grief is personal, that the state has no business regulating how people mourn. These are real arguments. They are also arguments that have been made, with varying degrees of success, by every industry that has ever profited from human vulnerability before regulators caught up.</p>
      <p>What is different here is the scale and the speed. Grieftech is not a niche product for the wealthy. The underlying models are becoming cheaper and more capable every few months. Within a few years, building a conversational reconstruction of a dead relative will require nothing more than a smartphone and access to that person's message history — which most of us already have. This is not a future problem. It is a present one that has not yet produced a crisis visible enough to force a policy response.</p>
      <p>That crisis will come. It will probably look like a lawsuit — a family torn apart over a deathbot one member built without the others' consent. Or a company going bankrupt and auctioning off its database of reconstructed dead people to the highest bidder. Or a story about someone who spent two years talking to an AI version of their spouse and emerged from grief not healed but more lost, having mourned a simulacrum instead of a person.</p>
      <p>We have laws about what happens to your house when you die. We have laws about your money, your intellectual property, your medical records. We have spent centuries developing frameworks for how the living inherit from the dead, and how the dead's wishes constrain the living.</p>
      <p>We have nothing about what happens to your voice. Nothing about your face. Nothing about the particular way you phrased things when you were tired, or the sign-off you used with people you loved, or the ten thousand small linguistic habits that made you recognizably you and not anyone else.</p>
      <p>All of that is, right now, free for the taking. And an entire industry has noticed.</p>
    `
  },
  {
    id: "the-number-that-built-indias-cities",
    category: "Public Policy",
    date: "Jun 26, 2026",
    isoDate: "2026-06-26",
    label: "An article on urban planning",
    theme: "FSI / CITY / HOUSING",
    cover: "cover-city",
    title: "The Number That Built India's Cities",
    excerpt: "In 1964, someone decided Mumbai's FSI would be 1.33. That decision — never voted on, barely debated — shaped where you live, what you pay for it, and why your commute takes two hours.",
    bodyHtml: `
      <p>There is a number that determines almost everything about how Indian cities look and feel. It decides how tall your building is. It decides how many people can afford to live near where they work. It decides whether a city sprawls outward for fifty kilometres or stacks upward and stays dense. It is not a natural law or a geographic fact. Someone chose it, in a meeting, decades ago, and it has been largely frozen in place ever since.</p>
      <p>The number is called the Floor Space Index. FSI. You have probably never heard of it. It runs your city anyway.</p>
      <p>FSI is simple in principle: it is the ratio of the total built-up area of a building to the plot of land it sits on. An FSI of 2 means you can build twice the area of your plot, spread across however many floors you like. An FSI of 1 means you can only build as much floor space as the land beneath you. The higher the FSI, the taller and denser a city can grow. The lower it is, the more it is forced to spread.</p>
      <p><a href="https://mru.org/courses/development-economics/floor-space-index-mumbai-india" target="_blank" rel="noreferrer">Mumbai's FSI, for most of its history, was 1.33 in the island city and just 1 in the suburbs.</a> This is not a typo. One of the most densely populated cities on earth, built on a narrow peninsula with nowhere to sprawl, was legally prevented from building upward by a number chosen in 1964. <a href="https://mumbai.citizenmatters.in/interview-sukriti-issar-fsi-mumbai-building-tdr-housing-policy-38026" target="_blank" rel="noreferrer">The key moment was 1964 when the 1.33 number was decided</a> — and it calcified into received wisdom so thoroughly that it took half a century and a full-blown housing catastrophe to begin revising it.</p>
      <p>For comparison: <a href="https://www.slideshare.net/slideshow/floor-space-index-fsi-in-indian-cities/39912020" target="_blank" rel="noreferrer">Singapore's business district has an FSI of 10. Manhattan's central business district has an FSI of 17.</a> Mumbai, at the peak of its commercial real estate market, was operating at 1.33. The consequence was entirely predictable and entirely predicted: when you cannot build up, prices go up. When prices go up, people who cannot afford them move further out. When they move further out, they spend two hours on a train getting to work.</p>
      <div class="stat"><div class="stat-item"><strong>1.33</strong>Mumbai's historic FSI cap</div><div class="stat-item"><strong>17</strong>Manhattan's FSI in its CBD</div><div class="stat-item"><strong>48 sq ft</strong>Average living space per person in Mumbai</div></div>
      <p><a href="https://mru.org/courses/development-economics/floor-space-index-mumbai-india" target="_blank" rel="noreferrer">The average living space per person in Mumbai is 48 square feet.</a> The United States federal government mandates a minimum of 50 square feet per person in prison cells. Mumbai's housing crisis is not a mystery. It is arithmetic.</p>
      <p>So why did the rule exist? The official reasoning was always about congestion — low FSI would prevent cities from becoming too dense, would protect infrastructure from being overwhelmed, would preserve some quality of urban life. These are not unreasonable goals. The problem is that they were achieved in exactly the wrong way. Limiting FSI does not reduce the number of people who need to live somewhere. It just determines where they end up living. In Mumbai's case, the answer was: in slums. <a href="https://mru.org/courses/development-economics/floor-space-index-mumbai-india" target="_blank" rel="noreferrer">The low FSI contributed directly to the proliferation of informal settlements across the city.</a> Dharavi — the largest slum in Asia, a settlement of a million people crammed into two square kilometres — exists partly because the formal housing market was structurally prevented from supplying enough units at prices ordinary people could afford.</p>
      <div class="stat cols-2"><div class="stat-item"><strong>~10 sq ft</strong><a href="https://thefederal.com/states/west/maharashtra/social-distancing-not-a-choice-in-dharavi-asias-biggest-slum" target="_blank" rel="noreferrer">Average per person in Dharavi (10–12 people per 100–120 sq ft home)</a></div><div class="stat-item"><strong>50 sq ft</strong>US federal minimum per person in a prison cell</div></div>
      <p>This is the dark irony at the heart of Indian urban planning: the rules meant to make cities liveable made them unliveable for most of the people who live in them.</p>
      <blockquote>Low FSI does not make a city less dense. It just determines who absorbs the density — and how.</blockquote>
      <p>Bengaluru tells a different version of the same story. Its FSI has historically been higher than Mumbai's — typically between 1.5 and 2.75 for residential — which sounds better until you realise that a city adding millions of people every decade still cannot build nearly enough housing near its employment centres. The result is not slums in the Mumbai sense but something equally dysfunctional: <a href="https://fourquarters.co.in/2025/09/08/floor-space-index-fsi-in-india-definition-formula-city-wise-comparison/" target="_blank" rel="noreferrer">vast horizontal sprawl</a>, ring roads extending further and further from the centre, entire IT campuses marooned in what used to be farmland, and a traffic problem so severe that the city has become a running joke about commute times. Bengaluru didn't go up because the rules made going up harder than going out. So it went out. And out. And out.</p>
      <div class="stat cols-4"><div class="stat-item"><strong>1.33</strong>Mumbai (historic)</div><div class="stat-item"><strong>2.75</strong>Bengaluru (residential)</div><div class="stat-item"><strong>10</strong>Singapore CBD</div><div class="stat-item"><strong>17</strong>Manhattan CBD</div></div>
      <p>The FSI story is also, inevitably, a story about who benefits from keeping things as they are. Low FSI artificially restricts the supply of floor space. Restricted supply with constant or growing demand means higher prices. Higher prices are extremely good for people who already own property. In India, as in most countries, existing property owners have significant political power — they vote, they donate, they sit on the committees that advise the municipalities that set the rules. The rules that keep their assets expensive are not difficult to maintain. Opponents of FSI reform routinely invoke infrastructure concerns and neighbourhood character and environmental protection, and these concerns are not entirely dishonest. But they also happen to align perfectly with the financial interests of people who bought cheap and would like prices to stay high.</p>
      <p><a href="https://questionofcities.org/how-redevelopment-ruined-mumbais-housing-and-marred-the-landscape/" target="_blank" rel="noreferrer">When Mumbai did eventually allow higher FSI through redevelopment schemes, the real estate lobby captured it almost immediately.</a> The model worked like this: developers were allowed increased FSI in exchange for providing free housing to slum dwellers. In practice, the free housing was tiny, the for-sale units built with the extra FSI were luxury apartments, and the government had effectively outsourced its housing responsibility to private builders whose interests pointed nowhere near affordability. The FSI went up. The housing crisis did not go away. The builders made money.</p>
      <p>This is the pattern that repeats. The rule is loosened. The loosening is captured. The underlying problem persists. And then someone proposes loosening the rule further, and the cycle begins again, with the same developers at the table and the same families on waiting lists.</p>
      <div class="stat cols-2"><div class="stat-item"><strong>2–5</strong><a href="https://housystan.com/article/understanding-mumbai-s-floor-space-index-fsi-and-its-impact-on-housing" target="_blank" rel="noreferrer">Mumbai's FSI under DCPR 2034 in certain zones</a></div><div class="stat-item"><strong>5.2</strong><a href="https://modernspaaces.com/blog/understanding-floor-space-index-fsi-definition-calculation-and-significance" target="_blank" rel="noreferrer">Karnataka's new premium FSI cap in industrial corridors</a></div></div>
      <p>Maharashtra has been gradually revising its FSI numbers upward — the DCPR 2034 now allows FSI between 2 and 5 in certain zones, depending on road width and proximity to transit. Karnataka revised its rules to allow premium FSI up to 5.2 in industrial corridors. These are real changes. Urban economists who have studied the issue for decades broadly agree that higher FSI, done right, is one of the most powerful tools available for making cities more affordable. The evidence from cities that have actually done it — Tokyo most notably, which kept FSI high and permitting easy and as a result has some of the most affordable housing of any major world city — is fairly clear.</p>
      <p>But “done right” is doing a lot of work in that sentence. Higher FSI without transit investment just creates denser traffic. Higher FSI without affordable housing requirements just creates more luxury supply. Higher FSI sold to developers as a reward for slum redevelopment creates the Mumbai model, where the numbers go up and the problem moves somewhere less visible.</p>
      <p>The deeper issue is that Indian city planning has never seriously reckoned with what cities are actually for. The low-FSI orthodoxy that calcified in the 1960s treated density as a problem to be contained rather than a resource to be organised. It treated the city as a physical object to be regulated rather than a labour market and a social system that needed to function. The people who set FSI at 1.33 in Mumbai were not monsters. They were planners doing what planners of that era did everywhere: applying modernist ideas about light, air, and space that made sense on paper and didn't account for a city of twenty million people that needed somewhere to put everyone.</p>
      <p>The number was wrong. It stayed wrong for sixty years. And the cities it shaped will spend the next sixty years dealing with the consequences — the sprawl, the slums, the commutes, the prices, the infrastructure deficit, the communities displaced by redevelopment that was supposed to help them.</p>
      <p>One number. Chosen in a meeting. Never voted on by the people who would live with it.</p>
      <p>That is urban planning. That is how cities actually get built.</p>
    `
  }
];
