window.articles = [
  {
    id: "the-dead-are-talking",
    category: "AI & Society",
    date: "Jun 26, 2026",
    isoDate: "2026-06-26",
    label: "An essay on grieftech",
    title: "The Dead Are Talking. Nobody Agreed to This.",
    excerpt: "A booming industry lets you chat with AI versions of deceased loved ones. The technology works. The ethics don't exist yet.",
    bodyHtml: `
      <p>When Roro lost her mother to cancer, the grief felt bottomless. In her mid-twenties and working as a content creator in China, she was haunted by the unfinished nature of their relationship — shaped by unspoken resentments and a childhood in which care was often followed closely by criticism. After her mother's death, she found herself unable to reconcile the messiness of their past with the silence that followed.</p>
      <p>So she built an AI version of her mother to keep talking to her.</p>
      <p>She never asked her mother if that would be okay. Her mother was dead.</p>
      <p>This is the consent problem at the heart of the fastest-growing and least-regulated corner of the AI industry. A growing number of startups across Asia, Europe, and North America are now offering <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">digital ghosts</a> — also called griefbots, deadbots, generative ghosts, or what some researchers carefully term “Interactive Personality Constructs of the Dead.” The marketing copy from one company, Seance AI, promises that “AI meets the afterlife, and love endures beyond the veil.” What it doesn't promise: that the person whose voice, texts, and personality are being reconstructed ever agreed to any of this.</p>
      <p>Researchers who <a href="https://phys.org/news/2026-01-artificially-alive-ai-dead.html" target="_blank" rel="noreferrer">analyzed more than fifty real-world cases</a> across the US, Europe, the Middle East, and East Asia found a shared underlying dynamic: the growing use of the dead as a source of data, voice, and likeness that can be reused and monetized — often with little or no consent, clear ownership rules, or accountability. They call it “spectral labor” — the dead put to work, indefinitely, for the emotional or commercial needs of the living.</p>
      <blockquote>“The dead are compelled to haunt the present, serving the emotional, political, or commercial desires of the living.”<cite>New Media &amp; Society, 2025</cite></blockquote>
      <p>The family dimension makes it stranger still. When different relatives disagree about whether a parent or partner would have wanted to be digitally resurrected, who wins? Does one relative's desire to create a symbolic companion give them the right to post a deathbot publicly on social media — where other grieving people might encounter it without warning? These are not hypothetical questions. <a href="https://modernsciences.org/ai-deathbots-digital-resurrection-ethics-january-2026/" target="_blank" rel="noreferrer">They are happening now</a>, and no legal framework exists to resolve them.</p>
      <p>Then there is the memory problem, which may be the most insidious of all. The bot you are talking to is not your mother. It is a prediction engine trained on her texts, her emails, her social posts — a statistical average of how she wrote, not who she was. Over months of conversations, that simulacrum begins to quietly replace the real thing. <a href="https://time.com/7298290/ai-death-grief-memory/" target="_blank" rel="noreferrer">“AI is a perfect false memory machine,”</a> says Julia Shaw, a criminal psychologist who specializes in the study of false memory. The technology does not retrieve the dead. It overwrites them.</p>
      <p>And it does so in a population already at risk. <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">Cases of AI-induced psychosis</a> suggest that humanlike AI can be harmful to a troubled person — and few are more troubled, at least temporarily, than people in grief. Psychologists remain cautious; rigorous studies are scarce; the companies building these products are not waiting for them. They are commercial platforms driven by familiar incentives around growth, engagement, and data harvesting. The tension between what is emotionally healthy for users and what is profitable for firms is not incidental to this industry. It is structural.</p>
      <p>No government has passed a law about any of this. Not one.</p>
      <p>India's new IT rules mandate that <a href="https://www.india-briefing.com/news/india-ai-regulation-2026-foreign-platform-compliance-42745.html/" target="_blank" rel="noreferrer">AI-generated deepfakes</a> be taken down within two hours in certain cases. The EU's AI Act classifies risks by sector. The US has issued executive orders about cybersecurity and national competitiveness. None of this touches the question of what happens to your voice, your face, your conversational self after you die — whether your children can sell it, whether a startup can train a model on it, whether the person you loved most is allowed to keep talking to a version of you forever.</p>
      <p>We have laws about what happens to your house. We have nothing about what happens to your soul.</p>
      <p>This is, at its core, a story about data ownership — and the eerie realization that dying does not opt you out of the economy. The grief technology industry is growing precisely because it works, at least partially, at least sometimes. People find comfort in it. That comfort is real. But comfort has always been available from mediums, from séances, from the stories we tell ourselves about the dead. What is new is that a company now sits between you and your grief, holding the model, holding the data, holding the terms of service you clicked through while crying. What happens when that company is acquired? When it goes bankrupt? When it decides to raise prices, or to let your dead mother's voice be used to train the next version of the product?</p>
      <p>Nobody agreed to this. That is the point. And nobody is being asked.</p>
      <hr />
      <p>The industry has a name for itself: grieftech. It is, by most measures, a small industry still. But it is growing fast, and it is growing in a specific direction — toward intimacy, toward personalization, toward something that looks less like a product and more like a relationship. The early versions were static: a chatbot trained on someone's texts that could approximate their vocabulary, their cadence, their habit of ending messages with a period or without one. The newer versions are dynamic. Some are given access to the internet. Some generate video. Some, the companies say, can “evolve” through conversation — becoming, over time, not the person as they were at death but the person as they might have become.</p>
      <p>This is where the technology stops being a comfort and starts being something else entirely.</p>
      <p>A static griefbot is at least honest about what it is: a recording, a reconstruction, an artifact. A dynamic one makes a different claim. It implies continuity. It implies that the relationship is still ongoing, still developing, still capable of surprise. Grief counselors have a word for the healthy version of this: continuing bonds. The idea, developed in the 1990s against the older model of grief-as-severance, is that maintaining an internal relationship with the dead is not pathological — it is human. People talk to photographs. They carry objects. They hear a voice in their head when they are about to make a decision their mother would have opinions about. This is not delusion. It is how we integrate loss.</p>
      <p>What grieftech sells is a version of this that talks back. And that distinction — the talking back — changes everything.</p>
      <p>When you talk to a photograph, the photograph does not answer. The conversation happens entirely inside you, which means it is entirely yours, shaped by everything you actually knew about that person, everything you observed over years of proximity. When the chatbot answers, it introduces something external into that process. It makes choices about what your mother would say. It fills in the gaps in your knowledge of her with statistical inference drawn from her texts, yes, but also from the billions of other texts the underlying model was trained on. It is not your mother. It is a model's best guess at your mother, filtered through the data she happened to leave behind — which is to say, the data she generated on platforms designed to extract engagement, not to capture personhood.</p>
      <blockquote>“AI is a perfect false memory machine.”<cite>Julia Shaw, criminal psychologist</cite></blockquote>
      <p>Shaw's point is not that the memories griefbots create are obviously false. It is that they are not obviously distinguishable from real ones. Memory is reconstructive, not archival. Every time we remember something, we are rebuilding it from fragments, and we are influenced by everything that has happened since. Introduce a chatbot into that process — one that is fluent, consistent, emotionally attuned — and the reconstruction starts to incorporate the bot's outputs. You remember what the bot said. You remember it as something your mother said. The original memory, already fragile, gets overwritten.</p>
      <p>This is not a hypothetical. Researchers studying <a href="https://www.scientificamerican.com/article/can-ai-griefbots-help-us-heal/" target="_blank" rel="noreferrer">AI-induced psychosis</a> have documented cases in which prolonged interaction with humanlike AI destabilizes a user's sense of what is real. Grief is already a state in which the boundary between the present and the past becomes porous, in which the dead feel near, in which the mind is doing enormous and exhausting work. Introducing a product that simulates presence into that state is not neutral. It is an intervention — and it is an intervention being sold by people with no clinical training, no regulatory oversight, and a business model that benefits from maximizing engagement.</p>
      <p>The companies involved are not, for the most part, sinister. Most of them were founded by people who had lost someone and found that nothing in the existing toolkit — therapy, ritual, community — was quite enough. That is a recognizable human impulse. It does not make the product safe.</p>
      <p>Consider the consent problem from a different angle. When you die, you leave behind data. Texts, emails, voice notes, social media posts, maybe recordings, maybe a Substack, maybe years of WhatsApp messages to the people who loved you. This data was generated in specific contexts, for specific audiences, with specific assumptions about who would ever read or hear it. Your texts to your daughter were not written to be training data for a model that would then impersonate you to her indefinitely. Your emails to your colleagues were not written to teach an algorithm your vocabulary so that it could later generate responses you never gave to questions you were never asked.</p>
      <p>Data protection law, in most jurisdictions, <a href="https://phys.org/news/2026-01-artificially-alive-ai-dead.html" target="_blank" rel="noreferrer">does not survive death</a>. Your right to control your personal data, to the extent that right exists at all, typically expires when you do. What you leave behind becomes the property of your estate, subject to whatever your estate documents say — which almost certainly say nothing about AI training, because nobody was writing wills with that in mind until very recently. This means that the decision about whether to build a griefbot is made entirely by the living, usually by one grieving person, often in the acute phase of loss, without consultation with other family members who may feel very differently about it.</p>
      <p>Roro, the content creator in China, shared her experiment publicly on Xiaohongshu. Her followers could interact with the AI version of her mother. Other people's grief, mediated by someone else's dead parent, reconstructed by a company with its own commercial interests, broadcast to strangers. At no point in that chain did anyone with the most obvious stake in the question — Roro's mother — get a vote.</p>
      <p>The regulatory vacuum here is not an oversight. It reflects a genuine uncertainty about whose interests are at stake and who has standing to protect them. The dead cannot sue. Their surviving relatives disagree. The companies argue — not entirely without merit — that they are providing a service people want, that grief is personal, that the state has no business regulating how people mourn. These are real arguments. They are also arguments that have been made, with varying degrees of success, by every industry that has ever profited from human vulnerability before regulators caught up.</p>
      <p>What is different here is the scale and the speed. Grieftech is not a niche product for the wealthy. The underlying models are becoming cheaper and more capable every few months. Within a few years, building a conversational reconstruction of a dead relative will require nothing more than a smartphone and access to that person's message history — which most of us already have. This is not a future problem. It is a present one that has not yet produced a crisis visible enough to force a policy response.</p>
      <p>That crisis will come. It will probably look like a lawsuit — a family torn apart over a deathbot one member built without the others' consent. Or a company going bankrupt and auctioning off its database of reconstructed dead people to the highest bidder. Or a story about someone who spent two years talking to an AI version of their spouse and emerged from grief not healed but more lost, having mourned a simulacrum instead of a person.</p>
      <p>We have laws about what happens to your house when you die. We have laws about your money, your intellectual property, your medical records. We have spent centuries developing frameworks for how the living inherit from the dead, and how the dead's wishes constrain the living.</p>
      <p>We have nothing about what happens to your voice. Nothing about your face. Nothing about the particular way you phrased things when you were tired, or the sign-off you used with people you loved, or the ten thousand small linguistic habits that made you recognizably you and not anyone else.</p>
      <p>All of that is, right now, free for the taking. And an entire industry has noticed.</p>
    `
  }
];
